language: go

go:
  - "1.10.x"

script:
  - make test
  - make lint
  - V3IO_TSDB_CONFIG="$TRAVIS_BUILD_DIR/travis_v3io.yaml" TSDB_TEST_TABLE_PATH="TSDB_INTEGRATION_TESTS/$TRAVIS_BUILD_NUMBER" make integration

before_deploy:
  - GOOS=linux GOARCH=amd64 make build
  - GOOS=darwin GOARCH=amd64 make build
  - GOOS=windows GOARCH=amd64 make build

deploy:
  provider: releases
  api_key:
    secure: SmTPBwa1Y5cZIvPzwftza/TRFE3DIV/FDarPQ8Wev8Rv5DQ6LVA9vCzGRBvrNDkP59ZYZlTqj+DZmiZvjtiWENq/AUBP5477s+e8/wyyrXMn5XDLO0Mwax1hhMNKxA/Hi2BaRDrSBCutOWXOSy/Ydltiuwhhwk6gdzJ8Lt4iJ5r8Xb/1CtuI8A2CqwVyj4b1G/uzVwnlzidNBj2qG6qebPHiUkX0v05iamB+pmk03e07td5Qd0FCsx23Ky8jivhMYzaim+7SlYy+81LhX/gkG9LY6sz5CZCdxjuYItN9um3yYDNI+KPUR2UgL72IcN6DFTyxeTgAS4gC8h/HaXuEKRoa5yW3kNJqum3xpvrKWjelTopjUcCtMabVSU93m2/I9tonYd7rbWFwVQQXezBY0AcaRDSahJHxCGAYvA5E5WxidI5BZkA+RI9lv7BVaDjbn3Gwer21RxJRVrIm0lWoN58SedD3BkKGXjfslxqzWnnle9x8er4ssHkFsCtgn/WnuSyZdfTbD3SWM0jpIC0n/M8lRq+QM6UTViWIRItlg08H/VlqVKQgpr14rcblNyNFKwREBg+iAXG08iJHoLFLTh9TjKN7FCj/F0b9lGD629xz8gVXFPeOFlfLyLrVWoU/Lrxy9k/nebvEeQN4cXSy40aKzkoLX94Ue5Gv5xlaiOY=
  file:
    - "$GOPATH/bin/tsdbctl-${TRAVIS_TAG}-linux-amd64"
    - "$GOPATH/bin/tsdbctl-${TRAVIS_TAG}-darwin-amd64"
    - "$GOPATH/bin/tsdbctl-${TRAVIS_TAG}-windows-amd64"
  skip_cleanup: true
  on:
    tags: true
