language: go

go:
  - "1.14.x"

env:
  - GO111MODULE=on TSDB_TEST_TABLE_PATH="TSDB_INTEGRATION_TESTS/$TRAVIS_BUILD_NUMBER"

script:
  - make test
  - make lint
  - V3IO_TSDB_CONFIG="$TRAVIS_BUILD_DIR/test/ci_v3io.yaml" make integration
  - V3IO_TSDB_CONFIG="$TRAVIS_BUILD_DIR/test/ci_v3io_bench.yaml" TSDB_BENCH_INGEST_CONFIG="$TRAVIS_BUILD_DIR/test/benchmark/testdata/tsdb-bench-test-config-ci.yaml" make bench

before_deploy:
  - GOOS=linux GOARCH=amd64 make build
  - GOOS=darwin GOARCH=amd64 make build
  - GOOS=windows GOARCH=amd64 make build
